### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by hoangpt1310** [DTCLC4/todo-list-ui#5]
## A collection of GitHub issue and pull request templates

*Update*: GitHub now also supports [multiple issue templates](https://help.github.com/articles/about-issue-and-pull-request-templates/).

~~GitHub finally supports [issue template](https://github.com/blog/2111-issue-and-pull-request-templates).~~

# What is an issue template?

[Issue and Pull Request templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)

# How to create issue templates?

- [About issue and pull request templates](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates)
- ~~[Manually creating a single issue template for your repository](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/)~~

# 10+ templates for you to pick!

Find your issue/PR templates, and just grab and go.

*Inspired by excellent GitHub projects that use issue and pull request templates.*

Templates here are either copied from or modified based on real projects on GitHub.

*See also [awesome-github-templates](https://github.com/devspace/awesome-github-templates) for more examples in real projects :tada:*

# Contribution

If you want to contribute to this project, send a PR directly instead of creating an issue.

## License

[![CC0](https://i.creativecommons.org/p/zero/1.0/88x31.png)](https://creativecommons.org/publicdomain/zero/1.0/)

To the extent possible under law, [Steve Mao](https://github.com/stevemao) has waived all copyright and related or neighboring rights to this work.

**Comment by dinhthi12** [comment]
Oh!

**Comment by tn0810520** [comment]
Ok
